version: "2.1"
services:
  nginx:
    build: .
    container_name: nginx
    depends_on:
      - web_service
    networks:
      - my-network
    ports:
      - 80:80

  web_service:
    build: https://github.com/kimbugp/movie-bookings.git
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_pass@database:5432/cinema
      - DEBUG=False
      - FLASK_APP=run.py
      - FLASK_ENV=production
    volumes:
      - ./:/code/
    networks:
      my-network:
        aliases:
          - flask-app
    depends_on:
      - database
    command: gunicorn run:app -b 0.0.0.0:5000

  database:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=cinema
    ports:
      - "5433:5432"
    expose:
      - "5432"

networks:
  my-network:
